//! The FIX dictionary generator, as a library (ADR-0207).
//!
//! One generator, three callers (ADR-0207 decision 1). It is loaded twice, the
//! way `fixbolt-sbe-gen` is (ADR-0081): by this crate's `build.rs` through
//! `#[path]`, to write the tables of [`crate::Fix44`] and, behind `fix50sp2`,
//! of the FIXT 1.1 / FIX 5.0 SP2 pair; and as this module, behind the
//! off-by-default `codegen` feature, for a user's own `build.rs`.
//!
//! - [`fix44_tables`] and `fixt11_fix50sp2_tables` (behind `fix50sp2`) are what `build.rs`
//!   writes to `$OUT_DIR/fix44.rs` and `$OUT_DIR/fixt11_fix50sp2.rs`, byte
//!   for byte (decision 2).
//! - [`generate`] is the user's door: an overlay onto the shipped FIX 4.4, or a
//!   whole FIX 4.4 file (decision 3), into one Rust file holding the user's own
//!   zero-sized type (decision 4). [`merged_model`] is the same merge without
//!   the writing: it answers what the generated type will answer, and reports
//!   the size of its tables.
//!
//! A user's `build.rs`, with `fixbolt-dict` as a build-dependency and the
//! `codegen` feature on:
//!
//! ```no_run
//! use fixbolt_dict::codegen::{self, Paths, Source};
//!
//! let overlay = std::fs::read_to_string("venue.xml")?;
//! let source = Source::Fix44Overlay(&overlay);
//! // Optional: a high custom tag widens every per-tag bitset; say so.
//! println!("cargo:warning={}", codegen::merged_model(source)?.table_size());
//! let rust = codegen::generate(source, "Venue", Paths::facade())?;
//! let out = std::path::PathBuf::from(std::env::var("OUT_DIR")?).join("venue.rs");
//! std::fs::write(out, rust)?;
//! println!("cargo:rerun-if-changed=venue.xml");
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! and in the crate, a module of its own — the file holds a format check, a
//! `tables` module (the free functions and statics the type answers from) and
//! the type with its two impls, and those names must not meet the crate's own:
//!
//! ```ignore
//! mod venue {
//!     include!(concat!(env!("OUT_DIR"), "/venue.rs"));
//! }
//! // venue::Venue implements Dictionary and Tables.
//! ```
//!
//! # The format check
//!
//! The build-dependency that writes the file and the dependency the file is
//! compiled against are two copies of `fixbolt-dict`, and nothing in cargo
//! makes them the same version. So the file opens with a compile-time check of
//! [`FORMAT_VERSION`] against the runtime crate's
//! (`tests/overlay.rs::the_generated_file_opens_with_its_format_check` holds
//! the emitted line to the text below). At the same format it compiles:
//!
//! ```
//! const _: () = assert!(
//!     ::fixbolt_dict::codegen_format::FORMAT_VERSION == 1,
//!     "Venue was generated by fixbolt-dict's codegen at format 1, and the fixbolt-dict it is compiled against reads another format: give the build-dependency and the dependency the same fixbolt version"
//! );
//! ```
//!
//! and a file written at another format does not — `E0080`, the constant's
//! evaluation failing on that sentence, not any other error:
//!
//! ```compile_fail,E0080
//! const _: () = assert!(
//!     ::fixbolt_dict::codegen_format::FORMAT_VERSION == 0,
//!     "Venue was generated by fixbolt-dict's codegen at format 0, and the fixbolt-dict it is compiled against reads another format: give the build-dependency and the dependency the same fixbolt version"
//! );
//! ```
//!
//! Where `build.rs` used to `die`, every function here returns a
//! [`GenError`]; nothing in this module panics, exits or indexes (CLAUDE.md §2
//! item 7). `parse` reads a document's fields and components, `merge` joins
//! two documents (the FIXT pair, or an overlay onto FIX 4.4), `model` holds
//! what one table is built from and computes it, `emit` writes it out.

mod emit;
mod error;
// Public only so `lib.rs` can re-export it as `codegen_format`; see there.
#[doc(hidden)]
pub mod format;
mod merge;
mod model;
mod parse;

use std::fmt::Write as _;

pub use error::GenError;
use error::refuse;
pub use format::FORMAT_VERSION;
pub use model::Model;
// `build.rs` loads this module by `#[path]` and never names the size; the
// library re-exports it for a user's `build.rs`.
use model::Spec;
#[allow(unused_imports)]
pub use model::TableSize;
use parse::{child, collect_components, collect_fields, refuse_empty_components};

/// The FIX 4.4 dictionary this crate ships, which an overlay is merged onto.
/// Read from inside the package, so it is there from a git tag and from a
/// `.crate` alike (ADR-0207 decision 3); never `NANOFIX_FIX44_XML`.
const SHIPPED_FIX44: &str = include_str!("../../spec/FIX44.xml");

/// What a user's dictionary is made from (ADR-0207 decision 3).
///
/// Both shapes are QuickFIX-format XML text. The first version is FIX 4.4 only
/// (decision 8); `#[non_exhaustive]` so overlays onto the FIXT 1.1 + FIX 5.0
/// SP2 pair can be added later without a breaking change.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Source<'a> {
    /// A `<fix>` document merged onto the `spec/FIX44.xml` this crate ships.
    ///
    /// Its `<header>`, `<messages>`, `<components>` and `<fields>` sections
    /// are each optional, and nothing else may appear (a `<trailer>` or a
    /// misspelt section is refused, not ignored). It adds and never removes or
    /// retypes:
    ///
    /// - a new `<field>` needs a number FIX 4.4 does not use; a field FIX 4.4
    ///   defines is repeated with its own number, name and type, and may gain
    ///   `<value>`s — if FIX 4.4 already lists values for it. A value FIX 4.4
    ///   lists is accepted whatever its description says;
    /// - a message FIX 4.4 defines is repeated with its own `msgtype` (and
    ///   `msgcat`, if given) and may gain fields, groups and components,
    ///   `required='Y'` included; a new message needs a `msgtype` FIX 4.4 does
    ///   not use;
    /// - a component FIX 4.4 defines may gain children; the header may gain
    ///   fields and groups;
    /// - no level of a message may end up carrying one field twice.
    ///
    /// A conflict fails naming both sides.
    Fix44Overlay(&'a str),
    /// A complete QuickFIX FIX 4.4 dictionary, generated as-is.
    Fix44Whole(&'a str),
}

/// How the emitted code names the items it implements and uses (ADR-0207
/// decision 4).
///
/// [`Paths::facade`] (the default) goes through `::fixbolt::dict::…`, so a user
/// depends on `fixbolt` at run time and on `fixbolt-dict` only as a
/// build-dependency. [`Paths::direct`] names `::fixbolt_dict` and
/// `::fixbolt_codec`, for this crate's own tests and for a user who drives the
/// engine without the facade.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Paths {
    root: Root,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum Root {
    #[default]
    Facade,
    Direct,
}

impl Paths {
    /// Paths through the `fixbolt` facade, `::fixbolt::dict::…`.
    #[must_use]
    pub const fn facade() -> Self {
        Self { root: Root::Facade }
    }

    /// Paths straight to `::fixbolt_dict` and `::fixbolt_codec`.
    #[must_use]
    pub const fn direct() -> Self {
        Self { root: Root::Direct }
    }

    const fn dictionary(self) -> &'static str {
        match self.root {
            Root::Facade => "::fixbolt::dict::Dictionary",
            Root::Direct => "::fixbolt_codec::Dictionary",
        }
    }

    const fn tables(self) -> &'static str {
        match self.root {
            Root::Facade => "::fixbolt::dict::Tables",
            Root::Direct => "::fixbolt_dict::Tables",
        }
    }

    const fn field_type(self) -> &'static str {
        match self.root {
            Root::Facade => "::fixbolt::dict::FieldType",
            Root::Direct => "::fixbolt_dict::FieldType",
        }
    }

    const fn format_version(self) -> &'static str {
        match self.root {
            Root::Facade => "::fixbolt::dict::codegen_format::FORMAT_VERSION",
            Root::Direct => "::fixbolt_dict::codegen_format::FORMAT_VERSION",
        }
    }
}

/// Generates one Rust file for the user to `include!`: a compile-time format
/// check, the tables in a module named `tables`, a unit struct named
/// `type_name`, and its `impl Dictionary` and `impl Tables` (ADR-0207
/// decision 4).
///
/// This is [`merged_model`] followed by writing it out. The size of the
/// tables is written into the file's opening comment; a `build.rs` that wants
/// it in the build log prints `merged_model(source)?.table_size()` as a
/// `cargo:warning` — this function prints nothing.
///
/// # Errors
///
/// Whatever [`merged_model`] refuses, and [`GenError::Dictionary`] if
/// `type_name` is not a Rust identifier, or is `tables`.
pub fn generate(source: Source<'_>, type_name: &str, paths: Paths) -> Result<String, GenError> {
    let model = merged_model(source)?;
    refuse_type_name(type_name)?;
    // The text depends on the merged model, the name and the paths, never on
    // which shape of source produced the model: an empty overlay and the
    // shipped file read whole write the same bytes.
    let what = "a FIX 4.4 dictionary";
    let banner = format!(
        "// @generated by fixbolt_dict::codegen from {what}.\n\
         // Do not edit. Regenerate from the XML, in the build script that wrote it.\n\
         // Tables: {}.\n\n",
        model.table_size()
    );
    let mut o = banner;
    let _ = writeln!(
        o,
        "const _: () = assert!(\n\
         \x20   {} == {FORMAT_VERSION},\n\
         \x20   \"{type_name} was generated by fixbolt-dict's codegen at format {FORMAT_VERSION}, and the fixbolt-dict it is compiled against reads another format: give the build-dependency and the dependency the same fixbolt version\"\n\
         );\n",
        paths.format_version(),
    );
    let _ = writeln!(
        o,
        "/// The tables [`{type_name}`] answers from.\n\
         #[allow(dead_code, missing_docs, clippy::pedantic)]\n\
         pub mod tables {{"
    );
    o.push_str(&emit::write(
        &model,
        &emit::Labels {
            dialect: type_name,
            banner: "",
            field_type: paths.field_type(),
        },
    )?);
    o.push_str("}\n\n");
    let _ = write!(
        o,
        "/// The dictionary generated from {what}, by `fixbolt_dict::codegen`\n\
         /// (ADR-0207): the type an engine, a session and a codec are generic over.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\n\
         pub struct {type_name};\n\
         \n\
         impl {dictionary} for {type_name} {{\n\
         \x20   #[inline]\n\
         \x20   fn is_header(tag: u32) -> bool {{\n\
         \x20       tables::is_header(tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn data_length_tag(tag: u32) -> Option<u32> {{\n\
         \x20       tables::data_length_tag(tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn group_delimiter(msg_type: &[u8], counter: u32) -> Option<u32> {{\n\
         \x20       // The head of the member list, never a table of its own.\n\
         \x20       match tables::group_members(msg_type, counter) {{\n\
         \x20           [first, ..] => Some(*first),\n\
         \x20           [] => None,\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn group_members(msg_type: &[u8], counter: u32) -> &'static [u32] {{\n\
         \x20       tables::group_members(msg_type, counter)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn group_order(msg_type: &[u8], counter: u32) -> &'static [u32] {{\n\
         \x20       // Declaration order already begins with the delimiter.\n\
         \x20       tables::group_members(msg_type, counter)\n\
         \x20   }}\n\
         }}\n\
         \n\
         impl {tables} for {type_name} {{\n\
         \x20   #[inline]\n\
         \x20   fn is_defined_tag(tag: u32) -> bool {{\n\
         \x20       tables::is_defined_tag(tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn is_defined_tag_for(_msg_type: &[u8], tag: u32) -> bool {{\n\
         \x20       // One file, one layer, as for Fix44.\n\
         \x20       tables::is_defined_tag(tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn required_header() -> &'static [u32] {{\n\
         \x20       tables::required_header()\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn required(msg_type: &[u8]) -> &'static [u32] {{\n\
         \x20       tables::required(msg_type)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn allows(msg_type: &[u8], tag: u32) -> bool {{\n\
         \x20       tables::allows(msg_type, tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn enum_allows(tag: u32, value: &[u8]) -> Option<bool> {{\n\
         \x20       tables::enum_allows(tag, value)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn field_type(tag: u32) -> Option<{field_type}> {{\n\
         \x20       tables::field_type(tag)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn is_msg_type(msg_type: &[u8]) -> bool {{\n\
         \x20       tables::is_msg_type(msg_type)\n\
         \x20   }}\n\
         \n\
         \x20   #[inline]\n\
         \x20   fn is_admin(msg_type: &[u8]) -> bool {{\n\
         \x20       tables::is_admin(msg_type)\n\
         \x20   }}\n\
         }}\n",
        dictionary = paths.dictionary(),
        tables = paths.tables(),
        field_type = paths.field_type(),
    );
    Ok(o)
}

/// A type name the emitted `pub struct` can carry: a Rust identifier, and not
/// `tables`, which the file's own module takes.
fn refuse_type_name(name: &str) -> Result<(), GenError> {
    let mut chars = name.chars();
    let identifier = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && name != "_";
    if !identifier || name == "tables" {
        return refuse(format!(
            "type name {name:?} cannot name the generated struct: it must be a Rust\n\
             identifier, and not `tables`, which the generated file's own module takes."
        ));
    }
    Ok(())
}

/// Merges `source` into the one dictionary a generated file is built from,
/// and returns it for inspection (ADR-0207 decision 3).
///
/// [`generate`] is this followed by writing it out, so a refusal here is the
/// build failure a user sees. The [`Model`] answers the questions the emitted
/// `impl Dictionary` and `impl Tables` answer — computed once, and written out
/// from the same computation — and [`Model::table_size`] is the size of the
/// tables it will emit.
///
/// # Errors
///
/// [`GenError::Xml`] if a text does not parse; [`GenError::Dictionary`] for
/// everything [`Source::Fix44Overlay`] lists as refused, and for everything
/// this crate's own `build.rs` refuses in a dictionary (an unknown field, a
/// DATA field without its length field, a message without `msgcat`, …). Each
/// sentence names what conflicts, both sides of it where there are two.
pub fn merged_model(source: Source<'_>) -> Result<Model, GenError> {
    match source {
        Source::Fix44Whole(text) => fix44_model(&parse_xml(text)?),
        Source::Fix44Overlay(text) => {
            let merged = merge::overlay_fix44(SHIPPED_FIX44, text)?;
            let doc = parse_xml(&merged)?;
            let model = fix44_model(&doc)?;
            merge::refuse_repeats(&doc)?;
            Ok(model)
        }
    }
}

impl Model {
    /// The tables alone, naming `crate::` — the text [`fix44_tables`] returns
    /// for the same dictionary. Hidden: it exists so a test can hold an empty
    /// overlay to [`crate::Fix44`]'s own bytes; a user's file comes from
    /// [`generate`].
    ///
    /// # Errors
    ///
    /// Only this generator's own arithmetic: the dictionary was checked when
    /// the model was built.
    #[doc(hidden)]
    pub fn crate_tables(&self) -> Result<String, GenError> {
        emit::write(self, &emit::Labels::crate_fix44())
    }
}

/// The FIX 4.4 tables this crate's `build.rs` writes to `$OUT_DIR/fix44.rs`,
/// from the dictionary text `xml` (`spec/FIX44.xml` unless
/// `NANOFIX_FIX44_XML` overrides it).
///
/// This crate's own tables, emitted for `crate::`-relative inclusion; a user's
/// dictionary comes from [`generate`].
///
/// # Errors
///
/// [`GenError::Xml`] if `xml` does not parse; [`GenError::Dictionary`] where
/// `build.rs` stops the build, carrying the same sentence.
pub fn fix44_tables(xml: &str) -> Result<String, GenError> {
    let doc = parse_xml(xml)?;
    fix44_from_document(&doc)
}

/// The FIXT 1.1 / FIX 5.0 SP2 tables this crate's `build.rs` writes to
/// `$OUT_DIR/fixt11_fix50sp2.rs`, from the **pair** of dictionary texts
/// (ADR-0080 decision 2, as narrowed by ADR-0083).
///
/// A component declared empty in one file and full in the other is taken
/// from the full one (ADR-0083 decision 4b); `build.rs` prints a
/// `cargo:warning` for it, and this function does not.
///
/// # Errors
///
/// [`GenError::Xml`] if either text does not parse; [`GenError::Dictionary`]
/// where `build.rs` stops the build, carrying the same sentence.
#[cfg(feature = "fix50sp2")]
pub fn fixt11_fix50sp2_tables(transport: &str, app: &str) -> Result<String, GenError> {
    let transport = parse_xml(transport)?;
    let app = parse_xml(app)?;
    pair_from_documents(&transport, &app, &mut Vec::new())
}

fn parse_xml(text: &str) -> Result<roxmltree::Document<'_>, GenError> {
    roxmltree::Document::parse(text).map_err(|e| GenError::Xml(e.to_string()))
}

/// The FIX 4.4 table, from one parsed file. `build.rs` parses the file itself,
/// so its not-well-formed message names the path.
pub(crate) fn fix44_from_document(doc: &roxmltree::Document<'_>) -> Result<String, GenError> {
    emit::write(&fix44_model(doc)?, &emit::Labels::crate_fix44())
}

/// The FIX 4.4 model, from one parsed file: the shipped one, a user's whole
/// file, or the shipped one with an overlay merged in.
fn fix44_model(doc: &roxmltree::Document<'_>) -> Result<Model, GenError> {
    let root = doc.root_element();
    let (number_of, type_of, enum_of) = collect_fields(root, "FIX44.xml")?;
    let (Some(header), Some(trailer)) = (child(root, "header"), child(root, "trailer")) else {
        return refuse("<header> or <trailer> section missing");
    };
    let Some(messages_el) = child(root, "messages") else {
        return refuse("<messages> section missing");
    };
    Model::compute(&Spec {
        dialect: "FIX 4.4",
        number_of,
        type_of,
        enum_of,
        components: {
            let map = collect_components(root);
            refuse_empty_components(&map, "FIX44.xml")?;
            map
        },
        messages: messages_el
            .children()
            .filter(|n| n.has_tag_name("message"))
            .collect(),
        header,
        trailer,
        length_exceptions: &[],
        // ADR-0083 decision 1's second rule, applied to FIX 4.4 by ADR-0084
        // decision 2's row: `18=2 A` is one legal two-value `ExecInst`, not one
        // illegal value. It was `false` here only until that row landed.
        per_token_enums: true,
    })
}

/// The FIXT 1.1 / FIX 5.0 SP2 table, from the pair.
///
/// Header, trailer and the eight admin messages come from the transport file;
/// fields, components, groups and the 156 application messages from the
/// application file. Every message — admin included — resolves its
/// `<component>` references against the **one** merged map, which is ADR-0083
/// decision 4 and the reason `NoMsgTypes(384)` reaches the Logon table at all.
///
/// A component one file leaves empty is reported in `warnings`, which
/// `build.rs` prints as `cargo:warning`s — before it looks at the result, so a
/// warning is shown even when a later refusal stops the build, as it was when
/// `build.rs` printed it itself.
#[cfg(feature = "fix50sp2")]
pub(crate) fn pair_from_documents(
    transport: &roxmltree::Document<'_>,
    app: &roxmltree::Document<'_>,
    warnings: &mut Vec<String>,
) -> Result<String, GenError> {
    let (troot, aroot) = (transport.root_element(), app.root_element());
    let (tnum, ttype, tenum) = collect_fields(troot, "FIXT11.xml")?;
    let (anum, atype, aenum) = collect_fields(aroot, "FIX50SP2.xml")?;
    // Taken before the merge, because after it there is no transport half left
    // to ask. ADR-0084 decision 1: what the transport file defines is a table
    // of its own, not a filter over the merged one.
    let transport_tags: Vec<u32> = tnum.values().copied().collect();
    let (number_of, type_of, enum_of) =
        merge::merge_fields((tnum, ttype, tenum), (anum, atype, aenum))?;

    let components = merge::merge_components(
        collect_components(troot),
        "FIXT11.xml",
        collect_components(aroot),
        "FIX50SP2.xml",
        warnings,
    )?;

    let (Some(header), Some(trailer)) = (child(troot, "header"), child(troot, "trailer")) else {
        return refuse("FIXT11.xml: <header> or <trailer> section missing");
    };
    let (Some(admin), Some(application)) = (child(troot, "messages"), child(aroot, "messages"))
    else {
        return refuse("<messages> section missing in FIXT11.xml or FIX50SP2.xml");
    };
    let messages: Vec<roxmltree::Node<'_, '_>> = admin
        .children()
        .filter(|n| n.has_tag_name("message"))
        .chain(application.children().filter(|n| n.has_tag_name("message")))
        .collect();

    // The transport file's own `<messages>`, by msgtype — the same node the
    // merged list is built from, so the two cannot name different sets.
    let transport_msg_types: Vec<&str> = admin
        .children()
        .filter(|n| n.has_tag_name("message"))
        .map(|m| match m.attribute("msgtype") {
            Some(mt) => Ok(mt),
            None => refuse("FIXT11.xml: <message> without msgtype"),
        })
        .collect::<Result<_, _>>()?;

    let model = Model::compute(&Spec {
        dialect: "FIXT 1.1 / FIX 5.0 SP2",
        number_of,
        type_of,
        enum_of,
        components,
        messages,
        header,
        trailer,
        length_exceptions: model::SP2_LENGTH_EXCEPTIONS,
        per_token_enums: true,
    })?;
    let mut out = emit::write(&model, &emit::Labels::crate_pair())?;
    out.push_str(&emit::emit_transport_layer(
        &transport_tags,
        &transport_msg_types,
    )?);
    Ok(out)
}
