//! What one generated table is built from, and the walks over it: required and
//! allowed tags, the header, and repeating groups — each descending through
//! `<component>` references.

use std::collections::{BTreeMap, BTreeSet};

use super::error::{GenError, refuse};
use super::parse::has_members;
use crate::field_type::FieldType;

/// A DATA or XMLDATA field whose length field the `{name}Len` / `{name}Length`
/// rule cannot find: `(data_tag, length_tag, data_name, length_name)`.
///
/// ADR-0083 decision 5. Consulted **only** after the name rule has failed, and
/// checked in both directions — an entry whose names or numbers the XML does
/// not carry, or that the name rule would have found anyway, fails the build.
/// The shape is `interop_quickfix_fields.rs::TYPE_EXEMPTIONS`'s.
pub(super) type LengthException = (u32, u32, &'static str, &'static str);

/// The one row measured on 2026-09-19 at pin `386ce46e`: 74 of FIX 5.0 SP2's 75
/// DATA fields and all 8 of its XMLDATA fields pair by name; this one
/// abbreviates `Security` to `Sec` in its length field's name.
///
/// A `tag - 1` fallback is refused rather than added: twelve SP2 DATA/XMLDATA
/// fields do not sit at `length + 1`, and a fallback pairs the wrong field
/// silently the next time upstream abbreviates a name.
#[cfg(feature = "fix50sp2")]
pub(super) const SP2_LENGTH_EXCEPTIONS: &[LengthException] = &[(
    41874,
    41873,
    "EncodedUnderlyingMarketDisruptionFallbackUnderlierSecurityDesc",
    "EncodedUnderlyingMarketDisruptionFallbackUnderlierSecDescLen",
)];

/// Everything one generated table is built from, however many XML files it came
/// from.
///
/// `fix44_from_document` fills it from one document; `pair_from_documents` merges two into
/// one under ADR-0083's rules and fills the same struct, so the emitter below
/// is one emitter and the two tables cannot drift apart in shape.
pub(super) struct Spec<'a, 'i> {
    /// Names this dialect in the generated doc comments.
    pub(super) dialect: &'static str,
    /// The `@generated by` banner's source clause.
    pub(super) source: &'static str,
    pub(super) number_of: BTreeMap<&'a str, u32>,
    /// The **variant**, not the XML spelling: `DATA` and `XMLDATA` are one
    /// type and the pair build depends on that (ADR-0083 decision 2).
    pub(super) type_of: BTreeMap<&'a str, FieldType>,
    pub(super) enum_of: BTreeMap<&'a str, Vec<&'a str>>,
    pub(super) components: BTreeMap<&'a str, roxmltree::Node<'a, 'i>>,
    pub(super) messages: Vec<roxmltree::Node<'a, 'i>>,
    pub(super) header: roxmltree::Node<'a, 'i>,
    pub(super) trailer: roxmltree::Node<'a, 'i>,
    /// ADR-0083 decision 5. Empty for FIX 4.4, one row for the pair.
    pub(super) length_exceptions: &'static [LengthException],
    /// Whether `enum_allows` splits a multi-value field on spaces before it
    /// checks the list. ADR-0083 decision 1's second rule. Both tables are now
    /// built with it: the pair from B1, FIX 4.4 from the row ADR-0084
    /// decision 2 gave it. The field stays because a table built to the
    /// whole-value reading is a thing this generator must still be able to
    /// say, and because the two spellings of the rule are then one line apart.
    pub(super) per_token_enums: bool,
}

/// A `<component>` reference that resolves to zero members, wherever it
/// appears. This is `collect_groups`'s `group {name} ... has no members` check
/// one level up — ADR-0083 decision 4's second refusal.
pub(super) fn refuse_empty_reference(
    def: roxmltree::Node<'_, '_>,
    name: &str,
    ctx: &str,
) -> Result<(), GenError> {
    if !has_members(def) {
        return refuse(format!(
            "{ctx} references component {name}, which resolves to zero members.\n\
             A component that splices in nothing loses every field under it in\n\
             silence — CLAUDE.md §2 item 5. ADR-0083 decision 4."
        ));
    }
    Ok(())
}

/// Required tags of an element, descending into required components.
///
/// A `<group required='Y'>` contributes its **counter** tag: that is the field
/// that appears on the wire. What is inside the group is required per entry, not
/// per message, and belongs to a different question.
///
/// `path` guards against a component cycle. FIX 4.4 has none — measured, deepest
/// nesting is 5 — but a generator that loops on a malformed dictionary hangs the
/// build with no message.
pub(super) fn collect_required<'a>(
    el: roxmltree::Node<'a, '_>,
    components: &BTreeMap<&'a str, roxmltree::Node<'a, '_>>,
    number_of: &BTreeMap<&str, u32>,
    msg: &str,
    out: &mut BTreeSet<u32>,
    path: &mut Vec<&'a str>,
) -> Result<(), GenError> {
    for c in el.children() {
        if c.attribute("required") != Some("Y") {
            continue;
        }
        let Some(name) = c.attribute("name") else {
            continue;
        };
        if c.has_tag_name("field") || c.has_tag_name("group") {
            match number_of.get(name) {
                Some(t) => {
                    out.insert(*t);
                }
                None => return refuse(format!("message {msg} names unknown field {name}")),
            }
        } else if c.has_tag_name("component") {
            let Some(def) = components.get(name) else {
                return refuse(format!("message {msg} names unknown component {name}"));
            };
            refuse_empty_reference(*def, name, &format!("message {msg}"))?;
            if path.contains(&name) {
                return refuse(format!("component cycle: {} -> {name}", path.join(" -> ")));
            }
            path.push(name);
            collect_required(*def, components, number_of, msg, out, path)?;
            path.pop();
        }
    }
    Ok(())
}

/// Every tag a message may carry: fields, group counters, and everything a
/// component splices in — all of it transitively.
///
/// Unlike [`collect_required`] this ignores `required`. "May carry" and "must
/// carry" are different questions and the corpus asks both, with different
/// `373` codes: 2 and 1.
pub(super) fn collect_allowed<'a>(
    el: roxmltree::Node<'a, '_>,
    components: &BTreeMap<&'a str, roxmltree::Node<'a, '_>>,
    number_of: &BTreeMap<&str, u32>,
    msg: &str,
    out: &mut BTreeSet<u32>,
    path: &mut Vec<&'a str>,
) -> Result<(), GenError> {
    for c in el.children() {
        let Some(name) = c.attribute("name") else {
            continue;
        };
        if c.has_tag_name("field") || c.has_tag_name("group") {
            match number_of.get(name) {
                Some(t) => {
                    out.insert(*t);
                }
                None => return refuse(format!("message {msg} names unknown field {name}")),
            }
            if c.has_tag_name("group") {
                collect_allowed(c, components, number_of, msg, out, path)?;
            }
        } else if c.has_tag_name("component") {
            let Some(def) = components.get(name) else {
                return refuse(format!("message {msg} names unknown component {name}"));
            };
            refuse_empty_reference(*def, name, &format!("message {msg}"))?;
            if path.contains(&name) {
                return refuse(format!("component cycle: {} -> {name}", path.join(" -> ")));
            }
            path.push(name);
            collect_allowed(*def, components, number_of, msg, out, path)?;
            path.pop();
        }
    }
    Ok(())
}

/// Every tag under `<header>`, descending into groups. The group's own counter
/// tag counts too: it is the field that appears on the wire.
pub(super) fn collect_header(
    el: roxmltree::Node<'_, '_>,
    number_of: &BTreeMap<&str, u32>,
    out: &mut BTreeSet<u32>,
) -> Result<(), GenError> {
    for c in el.children() {
        if !(c.has_tag_name("field") || c.has_tag_name("group")) {
            continue;
        }
        let Some(name) = c.attribute("name") else {
            return refuse("header entry without a name");
        };
        match number_of.get(name) {
            Some(t) => {
                out.insert(*t);
            }
            None => return refuse(format!("header names unknown field {name}")),
        }
        if c.has_tag_name("group") {
            collect_header(c, number_of, out)?;
        }
    }
    Ok(())
}

/// Every tag a group can hold, in declaration order, components spliced in
/// where they are referenced.
///
/// A nested `<group>` contributes its counter tag and nothing else: the counter
/// is the field that appears at this level of the wire, and what the nested
/// entries hold is the nested group's own question.
pub(super) fn collect_members<'a>(
    el: roxmltree::Node<'a, '_>,
    components: &BTreeMap<&'a str, roxmltree::Node<'a, '_>>,
    number_of: &BTreeMap<&str, u32>,
    ctx: &str,
    out: &mut Vec<u32>,
    path: &mut Vec<&'a str>,
) -> Result<(), GenError> {
    for c in el.children() {
        let Some(name) = c.attribute("name") else {
            continue;
        };
        if c.has_tag_name("field") || c.has_tag_name("group") {
            match number_of.get(name) {
                Some(t) => out.push(*t),
                None => return refuse(format!("{ctx} names unknown field {name}")),
            }
        } else if c.has_tag_name("component") {
            let Some(def) = components.get(name) else {
                return refuse(format!("{ctx} names unknown component {name}"));
            };
            refuse_empty_reference(*def, name, ctx)?;
            if path.contains(&name) {
                return refuse(format!("component cycle: {} -> {name}", path.join(" -> ")));
            }
            path.push(name);
            collect_members(*def, components, number_of, ctx, out, path)?;
            path.pop();
        }
    }
    Ok(())
}

/// Registers every group reachable from `el` under message type `mt`,
/// descending through components and through nested groups.
///
/// A group reached only through a component is the common case, not the
/// exception: `NoTradingSessions(386)` reaches NewOrderSingle solely through
/// `TrdgSesGrp`, so a walker that reads `<message>` children alone finds
/// nothing for it.
pub(super) fn collect_groups<'a>(
    el: roxmltree::Node<'a, '_>,
    components: &BTreeMap<&'a str, roxmltree::Node<'a, '_>>,
    number_of: &BTreeMap<&str, u32>,
    mt: &str,
    groups: &mut BTreeMap<(String, u32), Vec<u32>>,
    positions: &mut usize,
    path: &mut Vec<&'a str>,
) -> Result<(), GenError> {
    for c in el.children() {
        let Some(name) = c.attribute("name") else {
            continue;
        };
        if c.has_tag_name("group") {
            let Some(&counter) = number_of.get(name) else {
                return refuse(format!("message {mt} names unknown group counter {name}"));
            };
            let mut members = Vec::new();
            collect_members(
                c,
                components,
                number_of,
                &format!("group {name}"),
                &mut members,
                &mut Vec::new(),
            )?;
            if members.is_empty() {
                return refuse(format!("group {name} in message {mt} has no members"));
            }
            *positions += 1;
            match groups.entry((mt.to_string(), counter)) {
                std::collections::btree_map::Entry::Vacant(v) => {
                    v.insert(members);
                }
                std::collections::btree_map::Entry::Occupied(prev) => {
                    if prev.get() != &members {
                        return refuse(format!(
                            "counter {counter} appears twice in message {mt} with\n\
                             different members: {:?} then {members:?}.\n\
                             A (msg_type, counter) key cannot answer both.",
                            prev.get()
                        ));
                    }
                }
            }
            collect_groups(c, components, number_of, mt, groups, positions, path)?;
        } else if c.has_tag_name("component") {
            let Some(def) = components.get(name) else {
                return refuse(format!("message {mt} names unknown component {name}"));
            };
            refuse_empty_reference(*def, name, &format!("message {mt}"))?;
            if path.contains(&name) {
                return refuse(format!("component cycle: {} -> {name}", path.join(" -> ")));
            }
            path.push(name);
            collect_groups(*def, components, number_of, mt, groups, positions, path)?;
            path.pop();
        }
    }
    Ok(())
}
