//! A FIX 4.4 acceptor that speaks a venue's own dialect (ADR-0207).
//!
//! The dialect is `venue.xml`, an overlay onto the FIX 4.4 dictionary
//! `fixbolt-dict` ships. `build.rs` hands it to
//! `fixbolt_dict::codegen::generate`, which writes a zero-sized type,
//! [`venue::Venue`], implementing `Dictionary` and `Tables` — so a custom tag,
//! enum value, repeating group, header field, message type or required field is
//! validated, parsed and written from generated tables exactly as FIX 4.4's own
//! are. Nothing is read at run time.
//!
//! The same type is handed to both halves of the engine, and they must agree:
//! the encoding `TagValue<Venue, N>` to `fixbolt::serve_over`, which the
//! session validates by, and `App<_, N, P, S, Venue>`, which the handler reads
//! and writes by. `src/main.rs` shows the call; `tests/venue.rs` drives
//! [`Desk`] over a real socket.

/// The venue's dictionary, generated by `build.rs` from `venue.xml`.
///
/// A module of its own, because the generated file brings a `tables` module
/// and a format check with it, and those names must not meet this crate's.
pub mod venue {
    include!(concat!(env!("OUT_DIR"), "/venue.rs"));
}

use fixbolt::{Answer, GroupData, GroupEntryData, Handler, Incoming, Reply};
use venue::Venue;

/// `VenueClientID` — a custom body field, required on `NewOrderSingle`.
pub const VENUE_CLIENT_ID: u32 = 5001;
/// `VenueSessionTag` — a custom **header** field.
pub const VENUE_SESSION_TAG: u32 = 5002;
/// `NoVenueFees` — the counter of a custom repeating group.
pub const NO_VENUE_FEES: u32 = 5003;
/// `VenueFeeType` — a group member with its own enumerated values.
pub const VENUE_FEE_TYPE: u32 = 5004;
/// `VenueFeeAmt` — the group's delimiter: declared first, though its tag is
/// the higher one.
pub const VENUE_FEE_AMT: u32 = 5005;

/// The most fee entries echoed back. Held on the stack, so a reply never
/// allocates (non-negotiable 1, `benches/alloc.rs`); entries beyond it are not
/// echoed.
pub const MAX_FEES: usize = 8;

/// Fills every order, echoing what the venue's dialect added to it.
///
/// * `NewOrderSingle (D)` → an `ExecutionReport (8)` carrying the order's
///   `OrdType` (a custom value is echoed like any other), `VenueClientID`,
///   `VenueSessionTag` — which the reply writes in the header, because the
///   dictionary says it is one — and every `NoVenueFees` entry, written in the
///   order `venue.xml` declares, whatever order it is named in here.
/// * `VenueFeeReport (U1)`, a message type FIX 4.4 does not have → a
///   `VenueFeeAck (U2)` naming its `ClOrdID`.
/// * Anything else → a business reject.
#[derive(Debug, Default)]
pub struct Desk {
    fills: u32,
}

impl Handler<256, 64, 1024, Venue> for Desk {
    fn on_message(
        &mut self,
        msg: &Incoming<'_, 256, Venue>,
        reply: Reply<'_, 64, 1024, Venue>,
    ) -> Answer {
        match msg.msg_type() {
            b"D" => self.fill(msg, reply),
            b"U1" => reply
                .message(b"U2")
                .field(11, msg.get(11).unwrap_or_default())
                .send(),
            _ => reply
                .business_reject(
                    msg.seq().unwrap_or_default(),
                    msg.msg_type(),
                    3,
                    b"this desk takes orders and fee reports",
                )
                .send(),
        }
    }
}

impl Desk {
    fn fill(
        &mut self,
        msg: &Incoming<'_, 256, Venue>,
        reply: Reply<'_, 64, 1024, Venue>,
    ) -> Answer {
        self.fills = self.fills.wrapping_add(1);
        let mut digits = [0u8; 10];
        let exec_id = render(self.fills, &mut digits);

        // The group, read through the venue's tables. Each entry is named here
        // in tag order — type, then amount — and goes out in `venue.xml`'s
        // declared order, amount first: the order is the dictionary's, never
        // this call site's (non-negotiable 5).
        let mut rows: [[(u32, &[u8]); 2]; MAX_FEES] = [[(0, b""); 2]; MAX_FEES];
        let mut n = 0;
        if let Some(fees) = msg.view().group::<Venue>(b"D", NO_VENUE_FEES) {
            for (row, entry) in rows.iter_mut().zip(fees) {
                *row = [
                    (
                        VENUE_FEE_TYPE,
                        entry.get(VENUE_FEE_TYPE).unwrap_or_default(),
                    ),
                    (VENUE_FEE_AMT, entry.get(VENUE_FEE_AMT).unwrap_or_default()),
                ];
                n += 1;
            }
        }
        let entries = rows.each_ref().map(|fields| GroupEntryData {
            fields,
            groups: &[],
        });

        let mut m = reply.message(b"8");
        m.field(6, b"0")
            .field(11, msg.get(11).unwrap_or_default())
            .field(14, b"0")
            .field(17, exec_id)
            .field(37, exec_id)
            .field(39, b"0")
            .field(40, msg.get(40).unwrap_or_default())
            .field(54, msg.get(54).unwrap_or_default())
            .field(55, msg.get(55).unwrap_or_default())
            .field(150, b"0")
            .field(151, msg.get(38).unwrap_or_default());
        for tag in [VENUE_CLIENT_ID, VENUE_SESSION_TAG] {
            if let Some(value) = msg.get(tag) {
                m.field(tag, value);
            }
        }
        if n == 0 {
            return m.send();
        }
        m.group(NO_VENUE_FEES);
        m.send_with_groups(&[GroupData {
            counter: NO_VENUE_FEES,
            entries: entries.get(..n).unwrap_or_default(),
        }])
    }
}

/// ASCII digits of `v`, right-aligned in `buf`, without an allocation.
fn render(mut v: u32, buf: &mut [u8; 10]) -> &[u8] {
    let mut i = buf.len();
    loop {
        i -= 1;
        if let Some(d) = buf.get_mut(i) {
            *d = b'0' + u8::try_from(v % 10).unwrap_or(0);
        }
        v /= 10;
        if v == 0 || i == 0 {
            break;
        }
    }
    buf.get(i..).unwrap_or_default()
}
